### ISSUE TITLE
Gulp example doesn't work "out-of-box"

### ISSUE THREAD

**Issue by cikoriicabachkov** [ferdinandtorggler/remove-svg-properties#1]
Hello!
Example with gulp config doesn't work. I guess you need to change last line to:
`gulp.task('default', ['remove-svg-properties']);`

**Comment by ferdinandtorggler** [comment]
Hi,

I forgot to add gulp as a dependency, so doing `npm install` won't install gulp, thats why it's impossible to execute it. I fixed that now.
The gulpfile itself should be fine, since there is a `default` task defined. I don't see a `remove-svg-properties` task there, so I'm not sure how to use the line of code you posted. Anyway, it works with a simple `npm install` followed by `gulp` for me now, please check and let me know if your problem persists.
